/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventOfCode2018.day2

import java.io.File

fun main(args: Array<String>) {
    var twoCount = 0
    var threeCount = 0
    val fileName = "src/main/resources/boxIds.txt"
    File(fileName).inputStream().bufferedReader().useLines { lines -> lines.forEach { line ->
        val letterCount = mutableMapOf<Char, Int>()
        line.forEach {
            val count = letterCount.getOrDefault(it, 0) + 1
            letterCount[it] = count
        }

        if (letterCount.containsValue(2)) {
            twoCount++
        }

        if (letterCount.containsValue(3)) {
            threeCount++
        }
        }
    }

    println("The checksum is ${twoCount * threeCount}")
}
