/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventOfCode2018.day1

import java.io.File

fun main(args: Array<String>) {
    println(File("src/main/resources").absolutePath)
    var freq = 0
    val fileName = "src/main/resources/frequencyInput.txt"
    File(fileName).inputStream().bufferedReader().useLines { lines -> lines.forEach {
        freq += if (it[0] == '+') {
            it.substring(1).toInt()
        } else {
            it.toInt()
        }
    } }

    println("The frequency $freq")
}
